### ISSUE TITLE
Current oF poco lib source code version unclear

### ISSUE THREAD

**Issue by tgfrerer** [openFrameworks-cpp11/openFrameworks#1]
The libc++ poco libs were compiled from the currentmost stable poco release (poco-1.4.6p2-all) - which is most likely not the release/source originally compiled for OS X. I couldn't find any hints in the openFrameworks docs detailing which version of POCO was used - and the header files themselves are not too telling.

The include header files for POCO were left untouched.

TODO

* [x] figure out correct source code version, recompile

**Comment by tgfrerer** [comment]
since this repo is only here for historical reasons (and the issue been addressed in openframeworks/openframeworks), i'm closing this.

**Comment by bilderbuchi** [comment]
@tgfrerer I think we can nuke the whole repo/organization by now, no?

**Comment by tgfrerer** [comment]
(inflation adjusted) +1
